version: '3.7'
services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/myapp_development
  db:
    image: postgres:13
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  pgdata:
